---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/deploy-worker

run:
  path: pipeline-repo/ci/tasks/run-script.sh

params:
  VAULT_ADDR: {{vault-address}}
  VAULT_TOKEN: {{vault-token}}
  FOUNDATION_NAME: {{foundation-name}}
  PRODUCT_NAME: {{product-name}}

inputs:
- name: pipeline-repo
