---
name: ((deployment-name))
instance_groups:
- instances: 1
  name: cf-redis-broker
  networks:
  - name: ((network-name))
    static_ips:
    - ((broker-ip))
  persistent_disk_type: ((disk-type))
  properties:
    nats:
      machines: ((nats-ips))
      password: ((nats-password))
      port: ((nats-port))
      user: ((nats-username))
    route_registrar:
      routes:
      - health_check:
          name: redis-broker
          script_path: /var/vcap/jobs/cf-redis-broker/bin/health_check.sh
        name: broker_0
        port: 12350
        registration_interval: 10s
        tags:
          component: redis-broker
          env: production
        uris:
        - redis-broker.((cf-apps-domain))
  vm_type: ((vm-type))
  azs:
  - ((az))
  stemcell: trusty
  jobs:
  - name: cf-redis-broker
    release: cf-redis
  - name: route_registrar
    release: routing
  - name: syslog-configurator
    release: cf-redis
- instances: ((dedicated-nodes-count))
  name: dedicated-node
  networks:
  - name: ((network-name))
    static_ips: ((dedicated-nodes-ips))
  persistent_disk_type: ((disk-type))
  vm_type: ((vm-type))
  azs:
  - ((az))
  stemcell: trusty
  templates:
  - name: dedicated-node
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: ((network-name))
  properties:
    broker:
      host: redis-broker.((cf-apps-domain))
      name: redis
      password: ((broker-password))
      username: ((broker-username))
  vm_type: ((vm-type))
  azs:
  - ((az))
  stemcell: trusty
  templates:
  - name: broker-registrar
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: ((network-name))
  properties:
    broker:
      host: redis-broker.((cf-apps-domain))
      name: redis
      password: ((broker-password))
      username: ((broker-username))
  vm_type: ((vm-type))
  azs:
  - ((az))
  stemcell: trusty
  templates:
  - name: broker-deregistrar
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: smoke-tests
  networks:
  - name: ((network-name))
  vm_type: ((vm-type))
  azs:
  - ((az))
  stemcell: trusty
  templates:
  - name: smoke-tests
    release: cf-redis

properties:
  broker:
    host: redis-broker.((cf-apps-domain))
    name: redis
    password: ((broker-password))
    username: ((broker-username))
  cf:
    admin_password: ((cf-admin-password))
    admin_username: ((cf-admin-username))
    api_url: https://api.((cf-system-domain))
    apps_domain: ((cf-apps-domain))
    skip_ssl_validation: true
    system_domain: ((cf-system-domain))
  redis:
    agent:
      backend_port: 54321
    bg_save_command: ((bg-save-command-secret))
    broker:
      auth:
        password: ((broker-password))
        username: ((broker-username))
      backend_host: ((broker-ip))
      backend_port: 12345
      dedicated_nodes: ((dedicated-nodes-ips))
      dedicated_vm_plan_id: 48b35349-d3de-4e19-bc4a-66996ae07766
      enable_service_access: true
      host: ((broker-ip))
      name: redis
      network: ((network-name))
      route_name: redis-broker
      service_id: 7aba7e52-f61b-4263-9de1-14e9d11fb67d
      service_instance_limit: 5
      service_name: redis
      shared_vm_plan_id: 78bf886c-bc50-4f31-a03c-cb786a158286
      subdomain: redis-broker
    config_command: ((config-command-secret))
    host: ((broker-ip))
    maxmemory: 262144000
    save_command: ((save-command-secret))
  syslog_aggregator:
    address: ((syslog-aggregator-host))
    port: ((syslog-aggregator-port))

releases:
- name: cf-redis
  version: latest
- name: routing
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 6
  update_watch_time: 30000-180000

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

variables:
- name: config-command-secret
  type: password
- name: save-command-secret
  type: password
- name: bg-save-command-secret
  type: password
- name: broker-username
  type: password
- name: broker-password
  type: password
