name: ((deployment-name))
releases:
- name: redis
  version: "12"
  url: https://bosh.io/d/github.com/cloudfoundry-community/redis-boshrelease?v=12
  sha1: 324910eaf68e8803ad2317d5a2f5f6a06edc0a40
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: redis-leader-partition
  azs: [az1]
  stemcell: trusty
  vm_type: ((vm-size))
  instances: ((leader-insrances-count))
  jobs: 
  - name: redis
    release: redis
  networks:
  - name: ((network))
    static_ips:
    - ((leader-ip))
    properties:
      network: ((network))
      redis:
        password: ((redis-password))
- name: redis-partition
  jobs: 
  - name: redis
    release: redis
  azs: [az1]
  stemcell: trusty
  vm_type: ((vm-size))
  properties:
    network: ((network))
    redis:
      master: ((leader-ip))
      password: ((redis-password))
  resource_pool: medium
  update:
    canaries: 10
  instances: 2
  networks:
  - name: ((network))
- name: redis-test-slave-parition
  jobs: 
  - name: redis
    release: redis
  azs: [az1]
  stemcell: trusty
  vm_type: ((vm-size))
  properties:
    network: ((network))
    redis:
      master: ((leader-ip))
      password: ((redis-password))
      slave: ((slave-ip))
  resource_pool: medium
  update:
    canaries: 10
  instances: 1
  networks:
  - name: ((network))
    static_ips:
    - ((slave-ip))
- name: acceptance-tests
  jobs: 
  - name: acceptance-tests
    release: redis
  lifeycle: errand
    azs: [az1]
  stemcell: trusty
  vm_type: ((vm-size))
  properties:
    network: ((network))
    redis:
      master: ((leader-ip))
      password: ((redis-password))
      slave: ((slave-ip))
  resource_pool: medium
  update:
    canaries: 10
  instances: 1
  networks:
  - name: ((network))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
