groups:
- name: all
  jobs:
  - upload-bosh-releases
  - deploy
  - broker-registrar
- name: deploy
  jobs:
  - upload-bosh-releases
  - deploy
- name: errands
  jobs:
  - broker-registrar

resources:
- name: pipeline-repo
  type: git
  check_every: 4h
  source:
    uri: {{pipeline-repo}}
    branch: {{pipeline-repo-brunch}}

jobs:
- name: deploy
  plan:
  - get: pipeline-repo
  - task: deploy
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/generate-manifest.sh

- name: broker-registrar
  plan:
  - get: pipeline-repo
    passed: [deploy]
  - task: broker-registrar
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/run-errand.sh
      ERRAND: broker-registrar

- name: smoke-tests
  plan:
  - get: pipeline-repo
    passed: [broker-registrar]
  - task: broker-registrar
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/run-errand.sh
      ERRAND: smoke-tests
