groups:
- name: all
  jobs:
  - deploy
  - broker-registrar
  - smoke-tests
- name: deploy
  jobs:
  - deploy
- name: errands
  jobs:
  - broker-registrar
  - smoke-tests

resources:
- name: pipeline-repo
  type: git
  check_every: 4h
  source:
    uri: {{pipeline-repo}}
    branch: {{pipeline-repo-brunch}}

jobs:
- name: deploy
  plan:
  - get: pipeline-repo
  - task: deploy
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/generate-manifest.sh
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: broker-registrar
  plan:
  - get: pipeline-repo
    passed: [deploy]
  - task: broker-registrar
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/run-errand.sh
      ERRAND: broker-registrar
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}

- name: smoke-tests
  plan:
  - get: pipeline-repo
    passed: [broker-registrar]
  - task: broker-registrar
    file: pipeline-repo/ci/tasks/run-script.yml
    params: 
      SCRIPT: ci/tasks/run-errand.sh
      ERRAND: smoke-tests
      VAULT_ADDR: {{vault-address}}
      VAULT_TOKEN: {{vault-token}}
      FOUNDATION_NAME: {{foundation-name}}
      PRODUCT_NAME: {{product-name}}
